---
title: "SMMR Code"
date: "2024-07"
output: html_notebook
---


## Config

```{r}
source("./function.R")

# config 
senario_num <- 1
nsim <- 1000
n <- 500
p <- 20

# Setting the true value
beta_tre <- c(0.6, 0.6, 0.2, 0.6, 0.6, 0.6, rep(0, 14)) # True value of the outcome regression model for the treated group
beta_untre <- c(-0.6, 0.6, 0.2, -0.6, 0.6, 0.6, rep(0, 14)) # True value of the outcome regression model for the control group
alpha <- c(1, 1, 0.4, 0, 0, 0, 1, 1, 1.8, rep(0, 11)) # True value of the propensity score model
eta <- 2 # True ATE
gamma <- 0.75 # Degree of heterogeneous variance
tau <- c(0.25, 0.5, 0.75)
# Candidate regularization parameters (see Shortreed and Ertefaie, 2017).
lambda_vec = c(-10, -5, -2, -1, -0.75, -0.5, -0.25, 0.25, 0.49)
names(lambda_vec) = as.character(lambda_vec)
```

## Generating the true value of QTE

```{r}
n_true <- 200000
set.seed(1)

DAT <- as.data.frame(dat2(n_true, p, gamma, beta_tre, beta_untre, eta, senario_num))
colnames(DAT) <- c("Y1", "Y0")

Z1 <- quantile(DAT$Y1, probs = seq(0.0, 1, 0.01))
Z0 <- quantile(DAT$Y0, probs = seq(0.0, 1, 0.01))

true_qte <- Z1 - Z0
true_data <- as.data.frame(cbind(Z1, Z0, true_qte))
```

## Simulated data generation

```{r}
DAT.save <- list()

for (i in 1:nsim) {
    set.seed(i)
    DAT <- dat1(n, p, gamma, beta_tre, beta_untre, eta, alpha, senario_num)
    DAT <- cbind(scale(DAT[, 1:p]), DAT[, (p + 1):(p + 2)])
    DAT.save[[i]] <- DAT
}
```

## QOAL

```{r,warning=FALSE}
ps_qoal <- array(NA, dim = c(n, length(tau), nsim))
qoal <- matrix(nrow = nsim, ncol = length(tau))
colnames(qoal) <- paste0(tau, rep("01QOAL", length(tau)))


# Run the QOAL
for (i in 1:nsim) {
    set.seed(i)
  
    Data <- DAT.save[[i]]
    colnames(Data) <- c(paste("X", 1:p, sep = ""), "Y", "Z")
    
    for (k in 1:length(tau)) {
      res_qoal <- qoal_func(data = Data, tau = tau[k], lambda_vec = lambda_vec, gamma_conv = 2)
      
      ps <- res_qoal$ps
      coef_qoal[, k, i] = res_qoal$coef
        
      qoal[i, k] <- calcu_qte(Data$Y, Data$Z, ps, tau[k])
    }
}
```

## OAL

```{r,warning=FALSE}
oal <- matrix(nrow = nsim, ncol = length(tau))
colnames(oal) <- paste0(tau, rep("02OAL", length(tau)))
coef_oal <- array(NA, dim = c(p, 1, nsim))

for (i in 1:nsim) {
    set.seed(i)
    
    Data = data.frame(DAT.save[[i]])
    colnames(Data) = c(paste("X", 1:p, sep = ""), "Y", "Z")
    
    res_oal <- weight_lasso(data = Data, lambda_vec = lambda_vec, gamma_conv = 2, method = "OAL")
    
    ps <- res_oal$ps
    coef_oal[,,i] <- res_oal$coef
    
    oal[i, ] <- calcu_qte(Data$Y, Data$Z, ps, tau)
}

```

## Lasso

```{r}
lasso <- matrix(nrow = nsim, ncol = length(tau))
coef_lasso <- array(NA, dim = c(p, 1, nsim))
colnames(lasso) <- paste0(tau, rep("03lasso", length(tau)))

ps_form <- paste("Z", paste(paste0("X", 1:p), collapse = "+"), sep = "~")

for (i in 1:nsim) {
    set.seed(i)
    Data <- DAT.save[[i]]
    colnames(Data) <- c(paste("X", 1:p, sep = ""), "Y", "Z")
    
    lasso.model.cv <- cv.glmnet(x = as.matrix(Data[, 1:p]), y = as.matrix(Data$Z), family = "binomial", alpha = 1)
    bestlambda <- lasso.model.cv$lambda.min
    res <- glmnet(x = Data[, 1:p], y = Data$Z, lambda = bestlambda, family = "binomial", alpha = 1)
    
    coef_lasso[,,i] <- as.matrix(res$beta)
    ps <- predict(res, newx = as.matrix(Data[, 1:p]), s = lasso.model.cv$lambda.min, type = 'response')
    
    lasso[i, ] <- calcu_qte(Data$Y, Data$Z, ps, tau)
}
```

## Adl

```{r,warning=FALSE}
adl <- matrix(nrow = nsim, ncol = length(tau))
colnames(adl) <- paste0(tau, rep("04ADL", length(tau)))
coef_adl <- array(NA, dim = c(p, 1, nsim))

for (i in 1:nsim) {
    set.seed(i)
    
    Data = data.frame(DAT.save[[i]])
    colnames(Data) = c(paste("X", 1:p, sep = ""), "Y", "Z")
    
    res_adl <- weight_lasso(data = Data, lambda_vec = lambda_vec, gamma_conv = 2, method = "ADL")
    ps <- res_adl$ps
    
    coef_adl[,,i] <- res_adl$coef
    adl[i, ] <- calcu_qte(Data$Y, Data$Z, ps, tau)
}
```

## Targ_Var

```{r}
targ_var <- matrix(nrow = nsim, ncol = length(tau))
colnames(targ_var) <- paste0(tau, rep("05Targ_var", length(tau)))

targ_ex_ind <- which(beta_tre != 0)

for (i in 1:nsim) {
    set.seed(i)
    Data <- DAT.save[[i]]
    colnames(Data) <- c(paste("X", 1:p, sep = ""), "Y", "Z")
    
    for (k in 1:length(tau)) {
        if (tau[k] == 0.5) {
            ps_form <- paste("Z", paste(paste0("X", targ_ex_ind), collapse = "+"), sep = "~")
            res.glm <- glm(ps_form, data = Data, family = binomial(link = "logit"))
        } else {
            ps_form <- paste("Z", paste(paste0("X", c(targ_ex_ind, 10)), collapse = "+"), sep = "~")
            res.glm <- glm(ps_form, data = Data, family = binomial(link = "logit"))
        }
        ps <- res.glm$fitted.values
        
        targ_var[i, k] <- calcu_qte(Data$Y, Data$Z, ps, tau[k])
    } 
}
```

## Targ_Ex

```{r}
targ_ex <- matrix(nrow = nsim, ncol = length(tau))
colnames(targ_ex) <- paste0(tau, rep("06Targ_ex", length(tau)))

targ_ex_ind <- which(beta_tre != 0)
ps_form <- paste("Z", paste(paste0("X", targ_ex_ind), collapse = "+"), sep = "~")

for (i in 1:nsim) {
    set.seed(i)
    Data <- DAT.save[[i]]
    colnames(Data) <- c(paste("X", 1:p, sep = ""), "Y", "Z")
    
    res.glm <- glm(ps_form, data = Data, family = binomial(link = "logit"))
    ps <- res.glm$fitted.values
    
    targ_ex[i, ] <- calcu_qte(Data$Y, Data$Z, ps, tau)
}
```

## Conf

```{r}
conf <- matrix(nrow = nsim, ncol = length(tau))
colnames(conf) <- paste0(tau, rep("07Conf", length(tau)))

conf_ind <- which(beta_tre != 0 & alpha != 0)
ps_form <- paste("Z", paste(paste0("X", conf_ind), collapse = "+"), sep = "~")

for (i in 1:nsim) {
    set.seed(i)
    Data <- DAT.save[[i]]
    colnames(Data) <- c(paste("X", 1:p, sep = ""), "Y", "Z")
    
    res.glm <- glm(ps_form, data = Data, family = binomial(link = "logit"))
    ps <- res.glm$fitted.values
    
    conf[i, ] <- calcu_qte(Data$Y, Data$Z, ps, tau)
}
```

## PotConf

```{r}
potconf <- matrix(nrow = nsim, ncol = length(tau))
colnames(potconf) <- paste0(tau, rep("08PotConf", length(tau)))

potconf_ind <- which(beta_tre != 0 | alpha != 0)
ps_form <- paste("Z", paste(paste0("X", potconf_ind), collapse = "+"), sep = "~")

for (i in 1:nsim) {
    set.seed(i)
    Data <- DAT.save[[i]]
    colnames(Data) <- c(paste("X", 1:p, sep = ""), "Y", "Z")
    
    res.glm <- glm(ps_form, data = Data, family = binomial(link = "logit"))
    ps <- res.glm$fitted.values
    
    potconf[i, ] <- calcu_qte(Data$Y, Data$Z, ps, tau)
}

```

## Tabulation of results

```{r}
variable_name <- c("QOAL", "OAL", "Lasso", "ADL", "Targ_var", "Targ_ex", "Conf", "PotConf")
marge_res <- as.matrix(cbind(qoal, oal, lasso, adl, targ_var, targ_ex, conf, potconf))

tau_name <- paste0(as.character(tau * 100), "%")
true_value <- matrix(rep(true_data[tau_name, ]$true_qte, nsim), nrow = nsim, byrow = TRUE)
true_value_rep <- do.call(cbind, replicate(ncol(marge_res) / length(tau), list(true_value)))

marge_rbais <- (marge_res - true_value_rep) / true_value_rep
marge_rmse <- ((marge_res - true_value_rep) / true_value_rep) ^ 2

rbias <- colMeans(marge_rbais)
rrmse <- sqrt(colMeans(marge_rmse))
sd_res <- apply(marge_res, 2, sd)

res_sim <- cbind(rbias, rrmse, sd_res)
ind_col <- order(rownames(res_sim))
res_sim <- res_sim[ind_col, ]
res_sim <- cbind(
  res_sim[1:length(variable_name), ],
  res_sim[(length(variable_name) + 1):(length(variable_name) * 2), ],
  res_sim[(length(variable_name) * 2 + 1):(length(variable_name) * 3), ]
)
rownames(res_sim) <- variable_name

print(res_sim)
```


